// Generated by CoffeeScript 1.9.2
var Boom, fs, path, register, stylus;

stylus = require('stylus');

fs = require('fs');

path = require('path');

Boom = require('boom');

register = function(plugin, arg, next) {
  var cache, compress, ending, handler, home, linenos, prefix, route;
  route = arg.route, home = arg.home, compress = arg.compress, cache = arg.cache, ending = arg.ending, linenos = arg.linenos, prefix = arg.prefix;
  handler = function(request, reply) {
    var filename, pth, stylusName;
    filename = request.params.filename;
    filename = path.normalize(filename);
    if (filename.charAt(0) === '.') {
      return reply(Boom.notFound());
    }
    stylusName = filename.replace(/\.css$/, (ending ? ending : '.styl'));
    pth = home + "/" + stylusName;
    return fs.readFile(pth, 'utf8', function(err, content) {
      var style;
      if (err != null) {
        return reply(err.code ? Boom.notFound() : Boom.badImplementation(err));
      }
      style = stylus(content, {
        filename: pth,
        dest: home + "/" + filename,
        prefix: prefix || '',
        compress: compress != null ? compress : true,
        cache: cache != null ? cache : true,
        linenos: linenos != null ? linenos : false
      });
      return style.render(function(err, css) {
        if (err != null) {
          return reply(Boom.badImplementation(err));
        }
        return reply(css).type('text/css');
      });
    });
  };
  plugin.route([
    {
      method: 'GET',
      path: route || '/styles/{filename*}',
      handler: handler
    }
  ]);
  return next();
};

register.attributes = {
  multiple: true,
  pkg: require('../package.json')
};

module.exports = {
  register: register
};
