// Generated by CoffeeScript 1.7.1
var fs, path, register, stylus;

stylus = require('stylus');

fs = require('fs');

path = require('path');

register = function(plugin, _arg, next) {
  var handler, home, route;
  route = _arg.route, home = _arg.home;
  handler = function(request, reply) {
    var filename;
    filename = request.params.filename;
    filename = path.normalize(filename);
    if (filename.charAt(0) === '.') {
      return reply().code(404);
    }
    filename = filename.replace(/\.css$/, '.styl');
    return fs.readFile("" + home + "/" + filename, 'utf8', function(err, content) {
      if ((err != null ? err.code : void 0) === 'ENOENT') {
        return reply().code(404);
      }
      if (err != null) {
        return reply(plugin.hapi.error.internal(err.stack));
      }
      return stylus(content).set('filename', filename).set('compress', true).render(function(err, css) {
        if (err != null) {
          return reply(plugin.hapi.error.internal(err.message));
        }
        return reply(css).type('text/css');
      });
    });
  };
  plugin.route([
    {
      method: 'GET',
      path: route || '/styles/{filename*}',
      handler: handler
    }
  ]);
  return next();
};

register.attributes = {
  pkg: require('../package.json')
};

module.exports = {
  register: register
};
